### ISSUE TITLE
Camera Access in Mobile Browser

### ISSUE THREAD

**Issue by ercag** [PiotrFLEURY/camcode#11]
Hi,

i have some issiues but i'm not sure of these.

When i want to use my app in phone browser(iphone se 2 generation, safari) camera is not working. 
I'm just seing loading indicator but when i test it chrome on windows it is work properly.

**Comment by PiotrFLEURY** [comment]
Hi @ercag 

Sorry for the response time. I am in holidays. 

Do you run your app in HTTPS ? camera access on phones via web browsers are restricted to HTTPS protocol. Did you try on your iPhone with another web browser like Chrome ?

You can find more infos about running as HTTPS [here](https://github.com/PiotrFLEURY/camcode/issues/10#issuecomment-879699457)

Unfortunately, I dot not experiment any issue on my side.

Can you tell me if the demo page works on your phone ? [https://camcode-59c70.web.app/#/](https://camcode-59c70.web.app/#/)

**Comment by ercag** [comment]
Haa okay, i'd try over http probably https problem.

When i'm try your demo page this is perfectly fine.

Thank you for your support :)

Have a nice holidays

**Comment by PiotrFLEURY** [comment]
You're welcome.

Have a nice holidays too.
