### ISSUE TITLE
Camcode - different notes

### ISSUE THREAD

**Issue by nationsorg** [PiotrFLEURY/camcode#19]
Hi
Thank you for this project.
We wanted to create a non-profit app to scan the dangerous food products and tested your module.
Some notes:

1)
The scan area is bit small, can it take wider?

2)
We need to keep the camera close to the product, possible to make it more sensitive

3)
Important! Tested on Samsung S8 and Samsung S21 Android phones.
S21 cannot read the codebar.

Is it possible to contact you via email or other for more technical questions?

Thank you

**Comment by PiotrFLEURY** [comment]
Hi
Thank you to use my pugin.

A fix is in preparation on branch https://github.com/PiotrFLEURY/camcode/tree/fix/peeformances

For the moment potential fixes are :
- apply gray filter on snapshots for better decoding performances
- play with image compression
- play with snapshot dimenssion

If you have any idea to improve the scan, please let me know.

Feel free to test the fix branch et give me your feedbacks.

**Comment by nationsorg** [comment]
Hi, thank you for the answer !
Is there a way to show you in real time the difference of 2 scanner modules?
Do you accept the communication via email or other?

Thank you.

**Comment by nationsorg** [comment]
To which address?

**Comment by PiotrFLEURY** [comment]
My email address is on my Github profile

**Comment by nationsorg** [comment]
Hi, how are you? Did you return from vacances and we can discuss your module ? thanks

**Comment by PiotrFLEURY** [comment]
Hi, I'm fine thanks. I'm going to directly respond to your previous email.

**Comment by nationsorg** [comment]
Thank you, I can provide the real time demonstration of 2+ scripts, if you like so
